### ISSUE TITLE
Linux installation problems

### ISSUE THREAD

**Issue by hlolli** [rorywalsh/cabbage#2]
Hey Rory, I tried installing the newest master branch of Cabbage, encountered some problems

I started running confgureMakefiles.py

```
$ python ./configureMakefiles.py 
=================================================
======== Generate Makefiles for Cabbage =========
=================================================

This script will generate makefiles for Cabbage by
running the ProJUCEr application. Please make sure
you have already built the JUCE Projucer.

Usage:
python ./projucerConfig [../path_to/projucer]

python configureMakefiles.py ../../../JUCE/extras/Projucer/Builds/LinuxMakefile/build/Projucer

More info...
The standalone and plugin version of Cabbage use slightly different
JUCE and makefile configurations. This script creates makefiles 
using the Projucer, and then modifies them. The result is a single
code-base across both projects, and project makefiles that can be 
called without needing to constantly use the Projucer
/bin/sh: ../../../JUCE/extras/Projucer/Builds/LinuxMakefile/build/Projucer: No such file or directory
/bin/sh: ../../../JUCE/extras/Projucer/Builds/LinuxMakefile/build/Projucer: No such file or directory
```

So I thought, screw it, there a makefile there already so I did `make`
```
In file included from ../../JuceLibraryCode/include_juce_graphics.cpp:9:0:
../../JuceLibraryCode/modules/juce_graphics/juce_graphics.cpp:95:12: fatal error: ft2build.h: No such file or directory
   #include <ft2build.h>
            ^~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:397: build/intermediate/Debug/include_juce_graphics_f817e147.o] Error 1
```
and it ended here.

As I'm on Fedora25 using yum/dnf, I tried installing the following packages
```
freetype 2.7.1
freetype-devel 2.7.1
freetype-freeworld  2.7.1
mingw64-freetype 2.7.1
mingw64-freetype-static 2.7.1
```
none of which are provideing ft2build.h, is this header file deprecated?

I have juice installed and older installations of Cabbage worked for me in the past. Strange. But in the past freetype errors annyoed me but I was able to ignore them.

**Comment by rorywalsh** [comment]
You'll need to get the juce source and build the projucer. Then point the
Python for to that.

On 26 Sep 2017 7:21 p.m., "Hlöðver Sigurðsson" <notifications@github.com>
wrote:

Hey Rory, I tried installing the newest master branch of Cabbage,
encountered some problems

I started running confgureMakefiles.py

$ python ./configureMakefiles.py
=================================================
======== Generate Makefiles for Cabbage =========
=================================================

This script will generate makefiles for Cabbage by
running the ProJUCEr application. Please make sure
you have already built the JUCE Projucer.

Usage:
python ./projucerConfig [../path_to/projucer]

python configureMakefiles.py
../../../JUCE/extras/Projucer/Builds/LinuxMakefile/build/Projucer

More info...
The standalone and plugin version of Cabbage use slightly different
JUCE and makefile configurations. This script creates makefiles
using the Projucer, and then modifies them. The result is a single
code-base across both projects, and project makefiles that can be
called without needing to constantly use the Projucer
/bin/sh: ../../../JUCE/extras/Projucer/Builds/LinuxMakefile/build/Projucer:
No such file or directory
/bin/sh: ../../../JUCE/extras/Projucer/Builds/LinuxMakefile/build/Projucer:
No such file or directory

So I thought, screw it, there a makefile there already so I did make

In file included from ../../JuceLibraryCode/include_juce_graphics.cpp:9:0:
../../JuceLibraryCode/modules/juce_graphics/juce_graphics.cpp:95:12:
fatal error: ft2build.h: No such file or directory
   #include <ft2build.h>
            ^~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:397:
build/intermediate/Debug/include_juce_graphics_f817e147.o] Error 1

and it ended here.

As I'm on Fedora25 using yum/dnf, I tried installing the following packages

freetype 2.7.1
freetype-devel 2.7.1
freetype-freeworld  2.7.1
mingw64-freetype 2.7.1
mingw64-freetype-static 2.7.1

none of which are provideing ft2build.h, is this header file deprecated?

I have juice installed and older installations of Cabbage worked for me in
the past. Strange. But in the past freetype errors annyoed me but I was
able to ignore them.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/rorywalsh/cabbage/issues/2>, or mute the thread

**Comment by rorywalsh** [comment]
@hlolli I'm to close this? If you still have issues drop me a line, or reopen. Cheers.
