### ISSUE TITLE
Cabbage doesn’t find examples and *so files when started via symlinks

### ISSUE THREAD

**Issue by ech2** [rorywalsh/cabbage#8]
Hello.

I’m working on a package for the Arch User Repository. I install Cabbage to `/opt` and make executable symlinks to binaries in this directory from `/usr/bin`. The package layout is as follows:

```
/opt/
/opt/Cabbage/
/opt/Cabbage/Cabbage
/opt/Cabbage/CabbageLite
/opt/Cabbage/CabbagePluginEffect.so
/opt/Cabbage/CabbagePluginSynth.so
/opt/Cabbage/Examples/***
/opt/Cabbage/cabbage.png
/opt/Cabbage/opcodes.txt
/usr/
/usr/bin/
/usr/bin/Cabbage (symlink to ../../opt/Cabbage/Cabbage)
/usr/bin/CabbageLite (symlink to ../../opt/Cabbage/CabbageLite)
/usr/share/
/usr/share/applications/
/usr/share/applications/Cabbage.desktop
/usr/share/applications/CabbageLite.desktop
```

When I run cabbage with /usr/bin/Cabbage the Examples menu doesn’t get fetched with examples (the menu items are grayed out). Also Cabbage get’s confused regarding its root: it looks for the *so file in the home directory. It doesn’t happen when Cabbage is started directly or though .desktop entries.

It’s a minor issue, but it makes packaging hard. As all files should be in the same directory as executables, I can’t just copy everything to `/usr/local` or similar system directory.

FIY, here is the AUR packages I made: https://aur.archlinux.org/packages/cabbage-git

**Comment by rorywalsh** [comment]
Thanks for looking into this Eugene. It would be trivial enough to change the default locations if things to make them more Linux orientated. I won't be in a position to do much with this for a week or so. Can I ask you to leave it with me and I'll contact you as soon as I've time to look into it. Cheers.

**Comment by rorywalsh** [comment]
Hi @ech2 Is it ok for the .so files to be locating in usr/bin too or is this a Linux no-no? They should probably be in usr/lib or? I could set Cabbage up to look in both directories, starting with the current directory, and if not found proceed to usr/lib? I could do something similar with the examples. 

I can update the simple Cabbage desktop installer to so that it also installs to these directories if you think it's a good idea.

**Comment by ech2** [comment]
Hey @rorywalsh, thanks a lot for looking into this. I think it is fine to put the `.so` file to `/usr/bin`. I just checked, https://github.com/phantom-code/airwave does this. (this project works somewhat similarly by using a `.so` file that makes a LinuxVST out of any WinVST that lies in the same directory)

I’ll update my PKGBUILD over this weekend and tell you about the results.

**Comment by rorywalsh** [comment]
Glad you got it sorted.  I'll update my Linux script now so that it also installs Cabbage to these dirs too. `currentApplicationDirectory` will need to be changed in the case of Linux. I'll look into that too and let you know when it's done.

**Comment by rorywalsh** [comment]
Hey @ech2 I guess you also had to update the dummy.desktop file too?

**Comment by ech2** [comment]
Yes I did. I package my desktop entries in a package, see the Sources section here: https://aur.archlinux.org/packages/cabbage-git — I also package cabbage.png autistically cut to be of size 512x512

**Comment by rorywalsh** [comment]
Do you have that 512x512 png handy? I will use it too. I just pushed some changes to git in order for the IDE to find plugins in their new location on Linux. Didn't have a chance to test yet..

**Comment by ech2** [comment]
Here it is ![cabbage](https://user-images.githubusercontent.com/1007225/39181938-dedc80a6-47c3-11e8-9cef-f747e00e3708.png)

**Comment by rorywalsh** [comment]
Thanks for this Eugene. I've now updated the install script so that manual installations will push things to the same dirs as you use. One thing to note, I put the manual in:
`/usr/share/doc/cabbage/CabbageManual`
The manual, available in zip form [here](http://cabbageaudio.com/beta/CabbageManual.zip) extracts to a folder called CabbageManual. I figure it would be easier to stick with the folder name it extracts to. I also added a different png image for Cabbage lite which you can find [here](https://github.com/rorywalsh/cabbage/blob/master/Images/cabbagelite.png).   I'm going to close out this issue now. Feel free to reopen if anything pops up.
